import type { EnneagramType, Instinct, SubtypeContent } from '../types';

const subtype = (
  type: EnneagramType,
  instinct: Instinct,
  code: string,
  displayName: string,
  summary: string,
  themes: string[],
  tendencies: string,
  strengths: string,
  tensions: string,
  relationshipToType: string,
): SubtypeContent => ({ type, instinct, code, displayName, summary, themes, tendencies, strengths, tensions, relationshipToType });

export const SUBTYPES: SubtypeContent[] = [
  subtype(1, 'self-preservation', 'SP1', 'Worry', 'Improvement is directed toward practical order, reliability, and preventing everyday problems.', ['preparedness', 'self-discipline', 'practical order'], 'Often anticipates what could go wrong and quietly works to make the environment dependable.', 'Careful stewardship and durable standards.', 'Responsibility can harden into tension and difficulty resting.', 'The One’s standards become especially focused on safety, upkeep, and personal conduct.'),
  subtype(1, 'social', 'SO1', 'Non-Adaptability', 'Principles become a public reference point for how a group could function more fairly or correctly.', ['principle', 'example', 'shared standards'], 'Often teaches, models, or defends a system believed to serve the collective.', 'Ethical leadership and consistency under pressure.', 'Certainty about the right method can distance people with different approaches.', 'The One’s discernment is expressed through roles, institutions, and shared expectations.'),
  subtype(1, 'one-to-one', 'SX1', 'Zeal', 'Conviction gains heat and is applied directly to people, causes, and important bonds.', ['intensity', 'reform', 'directness'], 'Often challenges what feels compromised and tries to awaken the same conviction in others.', 'Courageous advocacy and catalytic honesty.', 'Urgency can feel corrective or overpowering in close relationships.', 'The One’s reforming drive becomes more personal, energetic, and confrontational.'),
  subtype(2, 'self-preservation', 'SP2', 'Privilege', 'Care is paired with a wish to be protected, welcomed, and allowed to receive without asking too plainly.', ['comfort', 'receiving', 'personal warmth'], 'Often creates an appealing, helpful presence while hoping others notice the needs beneath it.', 'Warmth, adaptability, and an inviting capacity for care.', 'Indirect needs can turn disappointment into entitlement or withdrawal.', 'The Two’s relational strategy becomes softer and more oriented to securing personal support.'),
  subtype(2, 'social', 'SO2', 'Ambition', 'Connection is built through visible contribution, influence, and becoming valuable to a wider network.', ['influence', 'recognition', 'contribution'], 'Often identifies where help or leadership will matter and moves toward consequential roles.', 'Social intelligence and generous mobilization of people.', 'Service can become tied to status or indispensability.', 'The Two’s need for connection is expressed through public usefulness and standing.'),
  subtype(2, 'one-to-one', 'SX2', 'Aggressive / Seductive', 'Attention concentrates on winning a particular bond through warmth, confidence, and emotional force.', ['attraction', 'pursuit', 'chosen bonds'], 'Often makes interest unmistakable and adapts quickly to what creates closeness.', 'Bold affection and a strong capacity to make another person feel seen.', 'Intensity may bypass boundaries or make reciprocity hard to assess.', 'The Two’s relational focus narrows into energetic pursuit of specific people.'),
  subtype(3, 'self-preservation', 'SP3', 'Security', 'Achievement is channeled into stability, competence, and producing tangible support.', ['work', 'stability', 'competence'], 'Often lets dependable output speak in place of overt self-promotion.', 'Practical effectiveness and sustained responsibility.', 'Worth can become fused with constant productivity and provision.', 'The Three’s success drive appears modest while remaining deeply invested in performance.'),
  subtype(3, 'social', 'SO3', 'Prestige', 'Success is measured against visible standards and the roles a culture recognizes.', ['reputation', 'leadership', 'excellence'], 'Often reads the room’s definition of success and presents an exceptionally capable version of self.', 'Strategic communication and inspiring public accomplishment.', 'Image can outpace contact with private values or limits.', 'The Three’s adaptive drive is most clearly expressed through status and social impact.'),
  subtype(3, 'one-to-one', 'SX3', 'Charisma', 'Achievement becomes interpersonal: embodying an ideal that attracts, inspires, or elevates a bond.', ['appeal', 'performance', 'partnership'], 'Often invests in presentation and in helping a chosen person or team shine.', 'Magnetic encouragement and responsive partnership.', 'Maintaining desirability can obscure fatigue or authentic disagreement.', 'The Three’s image awareness centers on chemistry and admired personal qualities.'),
  subtype(4, 'self-preservation', 'SP4', 'Tenacity', 'Longing and sensitivity are carried through endurance, effort, and a reluctance to advertise pain.', ['endurance', 'self-reliance', 'quiet depth'], 'Often proves identity by meeting hardship without asking for special handling.', 'Resilience and the ability to turn feeling into disciplined action.', 'Stoicism can conceal legitimate needs until depletion arrives.', 'The Four’s emotional intensity is contained and translated into practical perseverance.'),
  subtype(4, 'social', 'SO4', 'Shame', 'Difference is felt through comparison with the group and a keen awareness of what seems missing.', ['comparison', 'belonging', 'emotional truth'], 'Often names difficult feelings openly and searches for communities where complexity is understood.', 'Emotional honesty and sensitivity to exclusion.', 'Comparison may reinforce deficiency rather than clarify a workable next step.', 'The Four’s identity concerns unfold most visibly around belonging and social value.'),
  subtype(4, 'one-to-one', 'SX4', 'Competition', 'Longing becomes assertive, testing whether intensity can close the gap between self and what is desired.', ['competition', 'provocation', 'passion'], 'Often pushes against comparison by becoming more expressive, formidable, or impossible to overlook.', 'Creative force and willingness to confront emotional truth.', 'Envy can become rivalry or pressure placed on important relationships.', 'The Four’s search for significance gains directness, heat, and relational urgency.'),
  subtype(5, 'self-preservation', 'SP5', 'Castle', 'Knowledge and energy are protected inside a carefully controlled personal refuge.', ['privacy', 'boundaries', 'sufficiency'], 'Often minimizes needs and constructs a life that can operate with limited demands from others.', 'Deep focus, independence, and thoughtful use of resources.', 'Protection can become isolation or chronic under-participation.', 'The Five’s conserving pattern is strongest around space, time, and material autonomy.'),
  subtype(5, 'social', 'SO5', 'Totem', 'Belonging is sought through specialized knowledge, shared ideas, and respected areas of mastery.', ['expertise', 'ideas', 'affiliation'], 'Often connects through a subject, institution, or intellectual community that feels worth the energy.', 'Original scholarship and contribution to collective understanding.', 'Idealizing expertise can make ordinary participation or uncertainty feel exposing.', 'The Five’s distance is bridged through knowledge that offers a meaningful social role.'),
  subtype(5, 'one-to-one', 'SX5', 'Confidence', 'Privacy coexists with a wish for one unusually complete and trustworthy connection.', ['trust', 'depth', 'selectivity'], 'Often withholds broadly but shares an intense inner world with a carefully chosen person or pursuit.', 'Profound loyalty and concentrated imaginative depth.', 'Exacting trust tests can keep desired intimacy perpetually just out of reach.', 'The Five’s guardedness becomes selective openness in a bond deemed safe enough.'),
  subtype(6, 'self-preservation', 'SP6', 'Warmth', 'Security is cultivated through friendliness, dependable alliances, and reducing threat in the immediate environment.', ['support', 'caution', 'affiliation'], 'Often approaches uncertainty by building goodwill and checking that practical protections are in place.', 'Loyal cooperation and careful risk awareness.', 'Seeking safety through approval can weaken direct expression of doubt or anger.', 'The Six’s vigilance is softened into warmth and reciprocal protection.'),
  subtype(6, 'social', 'SO6', 'Duty', 'Uncertainty is managed through clear systems, commitments, and trusted standards of conduct.', ['duty', 'rules', 'reliability'], 'Often looks for an explicit framework that makes action legitimate and coordinated.', 'Principled loyalty and steadiness in responsible roles.', 'Rules can substitute for judgment when reality is ambiguous.', 'The Six’s search for certainty is directed toward authority, structure, and collective obligations.'),
  subtype(6, 'one-to-one', 'SX6', 'Strength / Beauty', 'Fear is met by projecting readiness, testing courage, and moving toward what feels threatening.', ['courage', 'challenge', 'intensity'], 'Often confronts uncertainty directly and values people who can withstand honest pressure.', 'Protective bravery and rapid action when stakes are real.', 'Countering fear with force can create the conflict that was anticipated.', 'The Six’s vigilance becomes energetic testing and visible personal strength.'),
  subtype(7, 'self-preservation', 'SP7', 'Keeper of the Castle', 'Possibility is organized into practical advantages, supportive networks, and a well-supplied life.', ['options', 'resources', 'networking'], 'Often spots useful opportunities and builds reciprocal arrangements that keep choices available.', 'Resourcefulness and upbeat practical problem-solving.', 'Pleasure and planning can rationalize excess or avoid difficult limits.', 'The Seven’s appetite for freedom becomes materially strategic and alliance-oriented.'),
  subtype(7, 'social', 'SO7', 'Sacrifice', 'Enthusiasm is invested in contribution and in being seen as someone who rises above personal appetite.', ['service', 'ideals', 'participation'], 'Often channels energy into causes, groups, or generous visions with broad benefit.', 'Hopeful leadership and inventive social contribution.', 'Self-denial can become an idealized image that hides resentment or private desire.', 'The Seven’s future focus is redirected toward collective possibility and moral aspiration.'),
  subtype(7, 'one-to-one', 'SX7', 'Suggestibility', 'Attention is captured by fascination, imaginative potential, and the charge of a new bond or idea.', ['fascination', 'novelty', 'imagination'], 'Often amplifies what is exciting and invites others into a vivid shared possibility.', 'Vision, playfulness, and infectious creative energy.', 'Anticipated magic can eclipse ordinary facts, follow-through, or warning signs.', 'The Seven’s optimism becomes especially relational, idealizing, and electrically focused.'),
  subtype(8, 'self-preservation', 'SP8', 'Satisfaction', 'Power is applied to securing essentials, maintaining autonomy, and meeting needs without delay.', ['survival', 'control', 'direct action'], 'Often acts decisively on practical obstacles and resists depending on uncertain systems.', 'Resourceful protection and calm action in material crises.', 'Self-reliance can become territoriality or impatience with vulnerability.', 'The Eight’s intensity concentrates on concrete security and personal sovereignty.'),
  subtype(8, 'social', 'SO8', 'Solidarity', 'Strength is used on behalf of allies, outsiders, or a group that deserves protection.', ['loyalty', 'justice', 'protection'], 'Often challenges unfair power and creates a durable circle of mutual defense.', 'Courageous advocacy and powerful group loyalty.', 'Protecting the collective can justify control or divide people into allies and adversaries.', 'The Eight’s force becomes social guardianship and resistance to unjust hierarchy.'),
  subtype(8, 'one-to-one', 'SX8', 'Possession', 'Intensity centers on impact, loyalty, and the wish for unfiltered engagement in close bonds.', ['impact', 'loyalty', 'merging'], 'Often seeks full presence and tests whether another person will meet equal strength.', 'Passionate commitment and transformative candor.', 'Demanding total engagement can crowd autonomy or escalate ordinary differences.', 'The Eight’s directness becomes most concentrated, magnetic, and personally possessive.'),
  subtype(9, 'self-preservation', 'SP9', 'Appetite', 'Comfort, routine, and familiar satisfactions create a buffer against disturbance and competing demands.', ['comfort', 'routine', 'grounding'], 'Often settles into reliable activities that make life feel manageable and pleasantly undramatic.', 'Grounded patience and appreciation for simple, sustaining rhythms.', 'Comfort can quietly replace action on priorities that carry emotional risk.', 'The Nine’s tendency to settle becomes focused on bodily ease and dependable habit.'),
  subtype(9, 'social', 'SO9', 'Participation', 'Belonging is maintained through steady involvement, useful roles, and attention to group cohesion.', ['participation', 'service', 'belonging'], 'Often works hard for the whole while making personal preferences difficult to detect.', 'Inclusive leadership and reliable community presence.', 'Busyness for others can conceal disconnection from a personal agenda.', 'The Nine’s merging pattern expands toward groups, teams, and shared purpose.'),
  subtype(9, 'one-to-one', 'SX9', 'Fusion', 'Harmony is sought through deep attunement to a particular person, purpose, or absorbing relationship.', ['attunement', 'union', 'adaptation'], 'Often experiences another’s energy and priorities as immediately vivid and compelling.', 'Tender receptivity and an unusual capacity for intimate presence.', 'Identification with the bond can blur boundaries and postpone individual direction.', 'The Nine’s receptivity becomes concentrated in one-to-one merging and shared momentum.'),
];

export function getSubtype(type: EnneagramType, instinct: Instinct) {
  return SUBTYPES.find((item) => item.type === type && item.instinct === instinct);
}

